name: Tests

on:
  push:
    branches: ["*"]
  pull_request:
  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: python -m playwright install --with-deps

      - name: Run unit test suite
        run: python scripts/run_tests.py --scope unit

  e2e:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: unit
    env:
      RUN_PLAYWRIGHT: "1"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: python -m playwright install --with-deps

      - name: Run E2E suite (skips if session unavailable)
        run: python scripts/run_tests.py --scope e2e
